apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: angularapp17
spec:
  selector:
    matchLabels:
      app: angularapp17
  replicas: 1
  template:
    metadata:
      labels:
        app: angularapp17
    spec:
      containers:
      - name: devopsdemo
        image: 10.168.131.38:5000/angularapp17
        ports:
         - containerPort: 80
