apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angularapp
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
      - name: angularapp
        image: 10.168.131.38:5000/angularapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
