apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angularapp17
  template:
    metadata:
      labels:
        app: angularapp17
    spec:
      containers:
      - name: devopsdemo
        image: 10.168.131.38:5000/angularapp17:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angularapp17-service
spec:
  selector:
    app: angularapp17
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

